version: "3.9"
services:
  wp:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp-content/plugins/studentenpack_posttypes.php:/var/www/html/wp-content/plugins/studentenpack_posttypes.php
      - ./wp-content/plugins/studentenpack_widgets.php:/var/www/html/wp-content/plugins/studentenpack_widgets.php
      - ./wp-content/themes/StudentenPACK:/var/www/html/wp-content/themes/StudentenPACK/
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: